quarkus:
  http:
    root-path: /api/v1
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url:
        jdbc:postgresql://localhost:5432/db
  hibernate-orm:
    database:
      generation: drop-and-create

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
