---
openapi: 3.0.3
info:
  title: Generated API
  description: Static OpenAPI definition
  version: "1.1"
paths:
  /api/v1/persons:
    get:
      tags:
        - Person Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: "#/components/schemas/Person"
    post:
      tags:
        - Person Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: "#/components/schemas/Person"
    delete:
      tags:
        - Person Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                uniqueItems: true
                type: array
                items:
                  $ref: "#/components/schemas/Person"
components:
  schemas:
    Person:
      type: object
      properties:
        givenName:
          type: string
        familyName:
          type: string
        age:
          format: int32
          type: integer
