quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/db
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    sql-load-script: import.sql
