---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: probes
  name: probes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: probes
  strategy: {}
  template:
    metadata:
      labels:
        app: probes
    spec:
      containers:
        - image: quay.io/xkridl/quarkus-hello-world:1.2
          name: quarkus-hello-world
          readinessProbe:
            httpGet:
              # path: /q/health/ready  # If wrong path, service will block the traffic into this pod
              path: /q/zdravicko/ready
              port: 8080
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              # path: /q/health/live   # If wrong path, kubelet will kill it
              path: /q/zdravicko/live
              port: 8080
            timeoutSeconds: 2
            failureThreshold: 5
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: probes
  name: probes
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: probes
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: probes
  name: probes
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: probes
    weight: null
status: {}
