quarkus:
  datasource:
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/db
  hibernate-orm:
    database:
      generation: validate
  flyway:
    migrate-at-start: true
