version: "3.8"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      app-db:
        condition: service_healthy
  app-db:
    container_name: app-db
    image: postgres:16.8
    volumes:
      - postgres-db:/var/lib/postgres/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "example-db"]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  postgres-db:

networks:
  app-network:
    name: app-network
    driver: bridge
