quarkus:
  log:
    handler:
      file:
        final-log-file-handler:
          enable: true
          path: /tmp/file-log.txt
    category:
      "org.jboss.pnc._userlog_":
        level: DEBUG
        handlers:
          - final-log-file-handler
