quarkus:
  rest:
    path: '/api/v1'
  http:
    port: 8089
  config:
    profile:
      parent: common
  datasource:
    # In case, we are using Postgre in the persistence.xml as the default datasource.
    # db-kind: postgresql
    # jdbc:
    #   url: jdbc:postgresql://localhost:5432/db
    # username: postgres
    # password: postgres

    # In case, we are using H2 in the persistence.xml as the default datasource.
    # db-kind: h2
    # jdbc:
    #  url: jdbc:h2:mem:h2;DB_CLOSE_DELAY=-1

    "h2":
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:h2;DB_CLOSE_DELAY=-1
    "pg":
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/db
      username: postgres
      password: postgres
  hibernate-orm:
    persistence-xml:
      ignore: true
    "h2":
      datasource: h2
      sql-load-script: no-file
    "pg":
      datasource: pg
      sql-load-script: import-postgres.sql

"%common":
  quarkus:
    hibernate-orm:
      "h2":
        database:
          generation: drop-and-create
        packages: com.example.model
      "pg":
        database:
          generation: drop-and-create
        packages: com.example.model

my-config:
  persistence-unit:
    available:
      - h2
      - pg
