openapi: 3.0.1
info:
  title: Contact API
  version: 1.0.0
servers:
  - url: http://localhost:8081/api/v1
    description: Generated server url
paths:
  /contacts:
    post:
      tags:
        - Contact
      summary: Create new contact
      operationId: createContact
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactRef'
        required: true
      responses:
        "201":
          description: Contact successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDto'
  /contacts/{id}:
    get:
      tags:
        - Contact
      summary: Get contact by ID
      operationId: getContactById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contact successfully returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactDto'
    delete:
      tags:
        - Contact
      summary: Delete contact by ID
      operationId: deleteContactById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Contact successfully deleted
components:
  schemas:
    ContactDto:
      required:
        - contact
        - type
      type: object
      properties:
        id:
          type: string
          description: ID of the contact
          example: "1"
        type:
          type: string
          description: Type of the contact
          example: EMAIL
          enum:
            - PHONE
            - EMAIL
        contact:
          type: string
          description: Contact itself
          example: john.doe@example.com
      description: Contact DTO used when returning to the client.
    ContactRef:
      required:
        - contact
        - type
      type: object
      properties:
        id:
          type: string
          description: ID of the contact
          example: "1"
        type:
          type: string
          description: Type of the contact
          example: EMAIL
          enum:
            - PHONE
            - EMAIL
        contact:
          type: string
          description: Contact itself
          example: john.doe@example.com
      description: Contact DTO intended to be used as a reference from another DTOs.
