spring:
  application:
    name: jpa-sandbox
  datasource:
    driver-class-name: org.postgresql.Driver
    username: example
    password: example
    url: jdbc:postgresql://localhost:5432/db
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
